# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

# do this before all your .NET Core tasks
steps:
- task: DotNetCoreInstaller@0
  inputs:

    # replace this value with the version that you need for your project
    # This version is forced by src/global.json used to force well-defined dotnet version
    # to avoid using beta version of newest dotnet if installed.
    version: '2.2.202'

- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: 'src'
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet tool install -g dotnet-sonarscanner
  workingDirectory: 'src'
  displayName: 'install sonar scanner'

- script: dotnet sonarscanner begin /k:"giolegal_web-bot" /o:"giolegal" /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=bb69e5b9d87a4313938f45638932685981ad0a69 /d:sonar.cs.opencover.reportsPaths="coverage.opencover.xml"
  workingDirectory: 'src'
  displayName: 'run sonar scanner'

# test and produce output for code coverage for sonar scanner
- script: dotnet test /p:CoverletOutputFormat=opencover /p:CoverletOutput=./opencover
  workingDirectory: 'src'
  displayName: 'dotnet test'


